export interface Recipe {
  id: string;
  title: string;
  description: string;
  ingredients: string[];
  category: "breakfast" | "lunch" | "dinner" | "snack" | "dessert";
  source: string;
  sourceUrl: string;
}

// Curated low-FODMAP recipes inspired by fodmapeveryday.com and theibsdietitian.com
export const RECIPES: Recipe[] = [
  {
    id: "1",
    title: "Lemon Herb Roast Chicken",
    description: "Juicy roast chicken with lemon, rosemary and thyme — naturally low-FODMAP when garlic and onion are skipped.",
    ingredients: ["chicken", "lemon", "rosemary", "thyme", "olive oil", "salt", "pepper"],
    category: "dinner",
    source: "FODMAP Everyday",
    sourceUrl: "https://www.fodmapeveryday.com/top-100-low-fodmap-recipes/",
  },
  {
    id: "2",
    title: "Grilled Chicken with Garlic-Infused Oil",
    description: "Smoky grilled chicken brushed with garlic-infused olive oil — flavor without the FODMAPs.",
    ingredients: ["chicken breast", "garlic-infused olive oil", "lemon", "paprika", "salt"],
    category: "dinner",
    source: "The IBS Dietitian",
    sourceUrl: "https://theibsdietitian.com/blog/50-easy-low-fodmap-recipes-for-you-to-try",
  },
  {
    id: "3",
    title: "Chicken & Rice Bowl",
    description: "Comforting bowl of jasmine rice, pan-seared chicken, carrots and spinach.",
    ingredients: ["chicken", "jasmine rice", "carrot", "spinach", "ginger", "tamari"],
    category: "lunch",
    source: "FODMAP Everyday",
    sourceUrl: "https://www.fodmapeveryday.com/top-100-low-fodmap-recipes/",
  },
  {
    id: "4",
    title: "One-Pan Chicken with Potatoes",
    description: "Crispy potatoes and chicken thighs roasted with chives and lemon zest.",
    ingredients: ["chicken thighs", "potatoes", "chives", "lemon zest", "olive oil"],
    category: "dinner",
    source: "The IBS Dietitian",
    sourceUrl: "https://theibsdietitian.com/blog/50-easy-low-fodmap-recipes-for-you-to-try",
  },
  {
    id: "5",
    title: "Pan-Seared Salmon with Dill",
    description: "Flaky salmon with fresh dill, lemon and a drizzle of olive oil.",
    ingredients: ["salmon", "dill", "lemon", "olive oil", "salt", "pepper"],
    category: "dinner",
    source: "FODMAP Everyday",
    sourceUrl: "https://www.fodmapeveryday.com/top-100-low-fodmap-recipes/",
  },
  {
    id: "6",
    title: "Shrimp Stir-Fry with Bok Choy",
    description: "Quick weeknight stir-fry with shrimp, bok choy and bell peppers in tamari sauce.",
    ingredients: ["shrimp", "bok choy", "red bell pepper", "ginger", "tamari", "rice"],
    category: "dinner",
    source: "The IBS Dietitian",
    sourceUrl: "https://theibsdietitian.com/blog/50-easy-low-fodmap-recipes-for-you-to-try",
  },
  {
    id: "7",
    title: "Beef & Zucchini Skillet",
    description: "Ground beef with zucchini, tomato and Italian herbs over polenta.",
    ingredients: ["ground beef", "zucchini", "tomato", "oregano", "basil", "polenta"],
    category: "dinner",
    source: "FODMAP Everyday",
    sourceUrl: "https://www.fodmapeveryday.com/top-100-low-fodmap-recipes/",
  },
  {
    id: "8",
    title: "Turkey Lettuce Wraps",
    description: "Ground turkey with carrots, water chestnuts and ginger wrapped in lettuce cups.",
    ingredients: ["ground turkey", "lettuce", "carrot", "water chestnuts", "ginger", "tamari"],
    category: "lunch",
    source: "The IBS Dietitian",
    sourceUrl: "https://theibsdietitian.com/blog/50-easy-low-fodmap-recipes-for-you-to-try",
  },
  {
    id: "9",
    title: "Quinoa Tabbouleh",
    description: "Bright, herby quinoa salad with parsley, mint, cucumber and lemon.",
    ingredients: ["quinoa", "parsley", "mint", "cucumber", "lemon", "olive oil", "tomato"],
    category: "lunch",
    source: "FODMAP Everyday",
    sourceUrl: "https://www.fodmapeveryday.com/top-100-low-fodmap-recipes/",
  },
  {
    id: "10",
    title: "Oven-Baked Cod with Vegetables",
    description: "Mild cod fillets baked with carrots, zucchini and fresh herbs.",
    ingredients: ["cod", "carrot", "zucchini", "thyme", "lemon", "olive oil"],
    category: "dinner",
    source: "The IBS Dietitian",
    sourceUrl: "https://theibsdietitian.com/blog/50-easy-low-fodmap-recipes-for-you-to-try",
  },
  {
    id: "11",
    title: "Maple Oatmeal with Strawberries",
    description: "Warm oats topped with strawberries, walnuts and a drizzle of maple syrup.",
    ingredients: ["oats", "strawberries", "walnuts", "maple syrup", "lactose-free milk"],
    category: "breakfast",
    source: "FODMAP Everyday",
    sourceUrl: "https://www.fodmapeveryday.com/top-100-low-fodmap-recipes/",
  },
  {
    id: "12",
    title: "Spinach & Feta Omelette",
    description: "Fluffy eggs with sautéed spinach and a sprinkle of feta cheese.",
    ingredients: ["eggs", "spinach", "feta", "olive oil", "chives"],
    category: "breakfast",
    source: "The IBS Dietitian",
    sourceUrl: "https://theibsdietitian.com/blog/50-easy-low-fodmap-recipes-for-you-to-try",
  },
  {
    id: "13",
    title: "Banana Buckwheat Pancakes",
    description: "Fluffy gluten-free pancakes made with ripe banana and buckwheat flour.",
    ingredients: ["banana", "buckwheat flour", "eggs", "lactose-free milk", "maple syrup"],
    category: "breakfast",
    source: "FODMAP Everyday",
    sourceUrl: "https://www.fodmapeveryday.com/top-100-low-fodmap-recipes/",
  },
  {
    id: "14",
    title: "Chia Pudding with Blueberries",
    description: "Overnight chia pudding with lactose-free milk and fresh blueberries.",
    ingredients: ["chia seeds", "lactose-free milk", "blueberries", "maple syrup", "vanilla"],
    category: "breakfast",
    source: "The IBS Dietitian",
    sourceUrl: "https://theibsdietitian.com/blog/50-easy-low-fodmap-recipes-for-you-to-try",
  },
  {
    id: "15",
    title: "Rice Noodle Chicken Soup",
    description: "Soothing broth with rice noodles, shredded chicken, ginger and bok choy.",
    ingredients: ["chicken", "rice noodles", "ginger", "bok choy", "carrot", "tamari"],
    category: "lunch",
    source: "FODMAP Everyday",
    sourceUrl: "https://www.fodmapeveryday.com/top-100-low-fodmap-recipes/",
  },
  {
    id: "16",
    title: "Caprese-Style Tomato Salad",
    description: "Ripe tomatoes with mozzarella, basil and a drizzle of olive oil.",
    ingredients: ["tomato", "mozzarella", "basil", "olive oil", "balsamic"],
    category: "lunch",
    source: "The IBS Dietitian",
    sourceUrl: "https://theibsdietitian.com/blog/50-easy-low-fodmap-recipes-for-you-to-try",
  },
  {
    id: "17",
    title: "Pork Tenderloin with Maple Glaze",
    description: "Tender pork roasted with a sweet-savory maple-mustard glaze.",
    ingredients: ["pork tenderloin", "maple syrup", "dijon mustard", "rosemary", "olive oil"],
    category: "dinner",
    source: "FODMAP Everyday",
    sourceUrl: "https://www.fodmapeveryday.com/top-100-low-fodmap-recipes/",
  },
  {
    id: "18",
    title: "Tuna Rice Cakes",
    description: "Crunchy rice cakes topped with tuna, cucumber and chives.",
    ingredients: ["tuna", "rice cakes", "cucumber", "chives", "lemon", "mayonnaise"],
    category: "snack",
    source: "The IBS Dietitian",
    sourceUrl: "https://theibsdietitian.com/blog/50-easy-low-fodmap-recipes-for-you-to-try",
  },
  {
    id: "19",
    title: "Peanut Butter Banana Smoothie",
    description: "Creamy smoothie with banana, peanut butter and lactose-free milk.",
    ingredients: ["banana", "peanut butter", "lactose-free milk", "oats", "cinnamon"],
    category: "snack",
    source: "FODMAP Everyday",
    sourceUrl: "https://www.fodmapeveryday.com/top-100-low-fodmap-recipes/",
  },
  {
    id: "20",
    title: "Dark Chocolate Strawberries",
    description: "Fresh strawberries dipped in melted dark chocolate — a simple low-FODMAP treat.",
    ingredients: ["strawberries", "dark chocolate"],
    category: "dessert",
    source: "The IBS Dietitian",
    sourceUrl: "https://theibsdietitian.com/blog/50-easy-low-fodmap-recipes-for-you-to-try",
  },
  {
    id: "21",
    title: "Lactose-Free Rice Pudding",
    description: "Creamy rice pudding made with lactose-free milk, vanilla and cinnamon.",
    ingredients: ["rice", "lactose-free milk", "vanilla", "cinnamon", "maple syrup"],
    category: "dessert",
    source: "FODMAP Everyday",
    sourceUrl: "https://www.fodmapeveryday.com/top-100-low-fodmap-recipes/",
  },
  {
    id: "22",
    title: "Roasted Carrot & Ginger Soup",
    description: "Velvety soup of roasted carrots blended with fresh ginger and chives.",
    ingredients: ["carrot", "ginger", "chives", "olive oil", "lactose-free cream"],
    category: "lunch",
    source: "The IBS Dietitian",
    sourceUrl: "https://theibsdietitian.com/blog/50-easy-low-fodmap-recipes-for-you-to-try",
  },
  {
    id: "23",
    title: "Beef & Bell Pepper Stir-Fry",
    description: "Sliced beef with red bell pepper and bok choy over jasmine rice.",
    ingredients: ["beef", "red bell pepper", "bok choy", "ginger", "tamari", "jasmine rice"],
    category: "dinner",
    source: "FODMAP Everyday",
    sourceUrl: "https://www.fodmapeveryday.com/top-100-low-fodmap-recipes/",
  },
  {
    id: "24",
    title: "Greek-Style Lemon Chicken Skewers",
    description: "Marinated chicken skewers with oregano, lemon and olive oil.",
    ingredients: ["chicken", "lemon", "oregano", "olive oil", "cucumber", "feta"],
    category: "dinner",
    source: "The IBS Dietitian",
    sourceUrl: "https://theibsdietitian.com/blog/50-easy-low-fodmap-recipes-for-you-to-try",
  },
];
