import { Meal } from "./meal";
import { DailyEntry } from "@/hooks/useDailyLog";
import { TriggerCorrelation } from "./triggerAnalysis";
import { format } from "date-fns";

export const buildDoctorReport = (
  meals: Meal[],
  daily: DailyEntry[],
  correlations: TriggerCorrelation[],
  toleratedManual: string[],
): string => {
  const now = new Date();
  const lines: string[] = [];

  lines.push(`# IBS Tracking Summary`);
  lines.push(`Generated: ${format(now, "PPP p")}`);
  lines.push(`Meals tracked: ${meals.length}`);
  lines.push(`Days with lifestyle data: ${daily.length}`);
  lines.push("");
  lines.push(`> This is a self-tracking summary, not a clinical diagnosis. Patterns are observational.`);
  lines.push("");

  // Symptom summary
  const sevCounts = { none: 0, mild: 0, moderate: 0, severe: 0 } as Record<string, number>;
  const symptomCounts: Record<string, number> = {};
  for (const m of meals) {
    sevCounts[m.symptom_severity] = (sevCounts[m.symptom_severity] ?? 0) + 1;
    for (const s of m.symptom_types) symptomCounts[s] = (symptomCounts[s] ?? 0) + 1;
  }
  lines.push(`## Symptom severity distribution`);
  lines.push(`- None: ${sevCounts.none}`);
  lines.push(`- Mild: ${sevCounts.mild}`);
  lines.push(`- Moderate: ${sevCounts.moderate}`);
  lines.push(`- Severe: ${sevCounts.severe}`);
  lines.push("");

  if (Object.keys(symptomCounts).length) {
    lines.push(`## Most reported symptoms`);
    for (const [s, c] of Object.entries(symptomCounts).sort((a, b) => b[1] - a[1]).slice(0, 8)) {
      lines.push(`- ${s}: ${c}`);
    }
    lines.push("");
  }

  // Suspected triggers
  if (correlations.length) {
    lines.push(`## Suspected triggers (observational)`);
    for (const c of correlations.slice(0, 12)) {
      const pct = Math.round(c.reactionRate * 100);
      lines.push(
        `- **${c.ingredient}** — reacted ${c.reactions}/${c.exposures} (${pct}%); confidence: ${c.confidence}`,
      );
      if (c.altExplanationHint) lines.push(`  - Note: ${c.altExplanationHint}`);
    }
    lines.push("");
  }

  // Tolerated
  if (toleratedManual.length) {
    lines.push(`## Foods user tolerates well (self-reported)`);
    lines.push(toleratedManual.map((x) => `- ${x}`).join("\n"));
    lines.push("");
  }

  // Bowel movements
  const allBM = daily.flatMap((d) => (d.bowelMovements ?? []).map((b) => ({ ...b, date: d.date })));
  if (allBM.length) {
    const bristolCounts: Record<number, number> = {};
    let urgency = 0, painful = 0, incomplete = 0, alarm = 0;
    for (const b of allBM) {
      bristolCounts[b.bristol] = (bristolCounts[b.bristol] ?? 0) + 1;
      if (b.urgency) urgency++;
      if (b.painful) painful++;
      if (b.incomplete) incomplete++;
      if (b.alarm) alarm++;
    }
    lines.push(`## Bowel movements (${allBM.length} logged)`);
    lines.push(`Bristol scale distribution:`);
    for (let i = 1; i <= 7; i++) {
      if (bristolCounts[i]) lines.push(`- Type ${i}: ${bristolCounts[i]}`);
    }
    lines.push(`- Urgency: ${urgency}`);
    lines.push(`- Painful: ${painful}`);
    lines.push(`- Incomplete evacuation: ${incomplete}`);
    if (alarm) lines.push(`- ⚠️ Episodes flagged with blood/mucus: ${alarm}`);
    lines.push("");
  }

  // Lifestyle averages
  const withStress = daily.filter((d) => typeof d.stress === "number");
  const withSleep = daily.filter((d) => typeof d.sleepQuality === "number");
  if (withStress.length || withSleep.length) {
    lines.push(`## Lifestyle averages`);
    if (withStress.length) {
      const avg = withStress.reduce((a, d) => a + (d.stress ?? 0), 0) / withStress.length;
      lines.push(`- Average stress (${withStress.length} days): ${avg.toFixed(1)} / 10`);
    }
    if (withSleep.length) {
      const avg = withSleep.reduce((a, d) => a + (d.sleepQuality ?? 0), 0) / withSleep.length;
      lines.push(`- Average sleep quality (${withSleep.length} days): ${avg.toFixed(1)} / 10`);
    }
    const alcoholDays = daily.filter((d) => d.alcohol).length;
    const caffeineDays = daily.filter((d) => d.caffeine).length;
    if (alcoholDays) lines.push(`- Days with alcohol: ${alcoholDays}`);
    if (caffeineDays) lines.push(`- Days with caffeine: ${caffeineDays}`);
    lines.push("");
  }

  lines.push(`---`);
  lines.push(`Generated by personal IBS tracker. Not a substitute for medical evaluation.`);

  return lines.join("\n");
};

export const downloadText = (filename: string, text: string) => {
  const blob = new Blob([text], { type: "text/markdown;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
};
